"""fix TokenModel

Revision ID: e9125d8c54f2
Revises: d0db66218559
Create Date: 2024-05-02 21:01:25.908021

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9125d8c54f2'
down_revision = 'd0db66218559'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tokens', sa.Column('expired_at', sa.BigInteger(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tokens', 'expired_at')
    # ### end Alembic commands ###
